[RUN]
run_name = run_1
output_path = ./output
num_runs = 1000
time_step = 1.0
traj_output = 0
x_aim = 2068512.138207
y_aim = 6025852.264654
z_aim = 0.0
theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
grav_error = 0
atm_error = 1
gnss_nav = 0
ins_nav = 0
filter_type = 0

[VEHICLE]
rv_type = 0

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 1.0
initial_vel_error = 0
initial_angle_error = 0
acc_scale_stability = 0.0
gyro_bias_stability = 0.0
gyro_noise = 0.0
gnss_noise = 0.0
