[RUN]
run_name = run_0
output_path = ./output
num_runs = 1000
time_step = 1.0
traj_output = 0
x_aim = 2068512.138207
y_aim = 6025852.264654
z_aim = 0.0
theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
# Gravitational error model
grav_error = 0
# Atmospheric perturbations
atm_error = 0
# Positioning updates during exoatmospheric flight
gnss_nav = 0
# If set to 0, indicates perfect acceleration measurements
ins_nav = 0
# If set to 1, enables idealized boost phase guidance
boost_guidance = 1
# Filters are currently not enabled
filter_type = 0

[VEHICLE]
rv_type = 0

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 1.0
initial_vel_error = 0
initial_angle_error = 0
acc_scale_stability = 0.0
gyro_bias_stability = 0.0
gyro_noise = 0.0
gnss_noise = 0.0
