[RUN]
run_name = run_0
output_path = ./output
num_runs = 10
time_step_main = 1.0
time_step_reentry = 0.01
traj_output = 0
# Note that the aimpoint coords are currently superseded by the thrust angle
x_aim = 0
y_aim = 0
z_aim = 0
theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
# Gravitational error model
grav_error = 1
# Atmospheric perturbations
atm_error = 1
# Positioning updates during exoatmospheric flight (1 is on, 0 is off)
gnss_nav = 0
# If set to 0, indicates perfect state measurements
ins_nav = 1
# If set to 1, enables idealized boost phase guidance
boost_guidance = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 0

[VEHICLE]
rv_type = 1

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 0.1
initial_vel_error = 1e-4
initial_angle_error = 1e-6
acc_scale_stability = 1e-6
gyro_bias_stability = 5e-8
gyro_noise = 1e-8
gnss_noise = 0