[RUN]
run_name = run_1
output_path = ./output
num_runs = 2
time_step = 0.1
traj_output = 1
x_aim = 2154991.342954
y_aim = 5995469.398617
z_aim = 0.0
theta_long = 0.785398163397
theta_lat = 0.0

[FLIGHT]
# Gravitational error model
grav_error = 1
# Atmospheric perturbations
atm_error = 1
# Positioning updates during exoatmospheric flight (1 is on, 0 is off)
gnss_nav = 0
# If set to 0, indicates perfect state measurements
ins_nav = 1
# If set to 1, enables idealized boost phase guidance
boost_guidance = 1
# If set to 1, enables RV proportional navigation w/ realistic maneuverability, if set to 2, idealized maneuverability
rv_maneuv = 1
# Filters are currently not enabled
filter_type = 0

[VEHICLE]
rv_type = 1

[ERRORPARAMS]
initial_x_error = 0.0
initial_pos_error = 1.0
initial_vel_error = 0
initial_angle_error = 0
acc_scale_stability = 0
gyro_bias_stability = 0
gyro_noise = 0
gnss_noise = 0
